# 服务器相关配置
server:
  # 服务端口
  port: 8087
  # 项目contextPath
  context-path: '/api'
  session:
  # session最大超时时间(分钟)，默认为30
    timeout: 30
    cookie:
      http-only: true

#静态资源路径映射及缓存时间
spring:
  mvc:
    static-path-pattern: '/static/**'
  resources:
    cache-period: 864000
          
  http:
    converters:
      #使用fastjson作为spring mvc JSON转换库
      preferred-json-mapper: 'fastjson'
      # Spring上传文件大小设置
    multipart: 
      max-file-size: 100Mb
      max-request-size: 128Mb
  #redis 配置
  redis:
    host: '192.168.1.151'
    password: 'admin123'
    port: 6379

# 主数据源，默认的
  datasource:
    #下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      type: 'com.alibaba.druid.pool.DruidDataSource'
      driver-class-name: 'com.mysql.jdbc.Driver'
      url: 'jdbc:mysql://192.168.1.181:8066/taxdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull'
      username: 'taxdb_user'
      password: 'taxdb_USER@378'
      #初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 50
      #配置获取连接等待超时的时间
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhifleIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: 'wall,stat'
#
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        urlPattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico, /druid/*'
      
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        urlPattern: '/druid/*'
      # Spring监控配置
      aop-patterns: 'com.yhsoft.api.service.impl.*'
  aop:
    proxy-target-class: true

mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
  configLocation: 'classpath:/mybatis-config.xml'
  check-config-location: true

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: 'com.yhsoft.framework.core.persistence.CustomMapper'
  not-empty: false
  identity: select replace(newid(), '-', '')
  ORDER: BEFORE



#项目配置
#config:
  #appName: '运营管理后台'
  #envrimont: dev
  #sms:
   # appKey: '1ead622ee783b'
  #upload:
    #系统类型 0-win, 1-linux 默认0
   # osType: 0
    #上传文件保存路径
    #window电脑上传路径
   # path: 'E:/web_root/upload'
    #苹果电脑上传路径
    #path: '/Users/yhios003/upload'

    #上传文件公共目录
  #  publicPath: 'upload'
    
# 微信公众号相关参数配置
wechat:
  mp:
    app-id: 'wx1a1b77f11a42a396'
    token: 'avq0sg0CeQOT7bUJHKUT2azcowAVTxLx'
    aes-key: 'ChtqcXLbvQwn3blN9DQk5UKInkwnNmzrQnKOHq32AAQ'
    secret: 'f3e5ba4db92a1802e2ecc493ebf9aa6a'
    base-url: 'http://asds.gtax.cn'    


